# Generated by Django 3.2.16 on 2024-03-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0003_auto_20240304_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecream',
            name='is_on_main',
            field=models.BooleanField(default=False, verbose_name='топпинг'),
        ),
    ]
