# Generated by Django 3.2.16 on 2024-03-06 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0008_auto_20240306_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icecream',
            options={'ordering': ('output_order', 'title'), 'verbose_name': 'мороженое', 'verbose_name_plural': 'Мороженое'},
        ),
    ]
